[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"
ar = "aarch64-linux-gnu-ar"
strip = "aarch64-linux-gnu-strip"
pkg-config = "aarch64-linux-gnu-pkg-config"

[build]
target-dir = "target"
